# -*- coding: utf-8 -*-
"""most_frequent_string.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tW65_mbGjChrtmQPAwssphPkNoZkvCfJ
"""

string=input("Enter the string ")
text=[None]*len(string)
for i in range(0,len(string)):
  text[i]=1
  for j in range(i+1,len(string)):
    if(string[i]==string[j]):
        text[i]=text[i]+1
        string=string[:j]+'0'+string[j+1:];
print("Character and their frequency");
for i in range(0,len(text)):
    if(string[i]!=' ' and string[i]!='0'):
        print(string[i]+"="+str(text[i]))

"""#Using dictionaries"""

import operator

if __name__ == '__main__':

    text = input("Enter the text : \n ")
    string_dict = dict()
    for letter in text:
        if letter not in string_dict:
            string_dict[letter] = text.count(letter)    
    ordered_answer = sorted(string_dict.items(), key=operator.itemgetter(1), reverse=True)
    print (ordered_answer)

input_string = input("Enter the text : \n ")
frequencies = {} 
  
for char in input_string: 
   if char in frequencies: 
      frequencies[char] += 1
   else: 
      frequencies[char] = 1

# Show Output
print ("Per char frequency in '{}' is :\n {}".format(input_string, str(frequencies)))

"""#Using collections.Counter()"""

from collections import Counter

input_string = input("Enter the text : \n ")

frequency = Counter(input_string)

# Show Output
print ("char frequency in '{}' is :\n {}".format(input_string, str(frequency)))
#Show type
print ("Type of frequency_per_char is: ", type(frequency))

"""#Using Python set()"""

input_string = input("Enter the text : \n ")

frequency = {char : input_string.count(char) for char in set(input_string)} 

# Show Output
print ("Character frequency table for '{}' is :\n {}".format(input_string, str(frequency)))